import Header from '@/components/Header';
import { Sidebar } from '@/components/Sidebar';
import { CollapseSidebarProvider } from '@/contexts/CollapseSidebar.context';
import { Sparkles } from 'lucide-react';
import Link from 'next/link';

export const metadata = {
  title: 'Spectrum - Discover creators',
  description: 'Generated by create next app',
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="relative h-screen lg:bg-[#ddd8ff]">
      <header className="py-5 px-6 lg:px-8">
        <div className="flex">
          <Link href="/" className="flex items-center gap-x-2">
            <span>
              <Sparkles className="w-7 h-7 lg:w-8 lg:h-8" />
            </span>
            <span className="font-black text-xl lg:text-2xl">Spectrum</span>
          </Link>
        </div>
      </header>
      {/* <div className="pb-[72px] xl:pb-20" /> */}
      {children}
    </main>
  );
}
