import Header from '@/components/Header';
import { Sidebar } from '@/components/Sidebar';
import { CollapseSidebarProvider } from '@/contexts/CollapseSidebar.context';

export const metadata = {
  title: 'Spectrum - Discover creators',
  description: 'Generated by create next app',
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <CollapseSidebarProvider>
      <Header />
      <div className="pb-[72px] xl:pb-20" />
      <div className="flex">
        <Sidebar />
        {children}
      </div>
    </CollapseSidebarProvider>
  );
}
