import NextTopLoader from 'nextjs-toploader';
import { AuthProvider } from '@/contexts/JWTContext';
import { GraphQlProvider } from '@/lib/apollo';
import '@/styles/globals.css';

export const metadata = {
  title: 'Discover creators',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NextTopLoader color="#6a57e3" height={4} showSpinner={false} />
        <AuthProvider>
          <GraphQlProvider>{children}</GraphQlProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
