import './globals.css';
import { Inter } from 'next/font/google';
import Header from '@/components/Header';
import { Sidebar } from '@/components/Sidebar';
import { CollapseSidebarProvider } from '@/contexts/CollapseSidebar.context';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Discover creators',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CollapseSidebarProvider>
          <Sidebar />
          <Header />
          <div className="pb-[72px] xl:pb-20" />
          {children}
        </CollapseSidebarProvider>
      </body>
    </html>
  );
}
