import { AuthProvider } from '@/contexts/JWTContext';
import '@/styles/globals.css';

export const metadata = {
  title: 'Discover creators',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
